version: "3.7"

services:
  python:
    build: .
    ports:
      - "5000:5000"

  redis:
    image: redis:alpine3.10
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"